```{r}
library(reticulate)
library(exams)

dlist <- function(lista, rem){
  return (lista[lista %in% rem == FALSE])
}

dig = -9:9
a <- 0
b <- 0
while (a==0 & b==0) {
  a = sample(dig,1)
  b = sample(dig,1)
}

c = sample(dlist(dig,0),1)
w = sample(dlist(dig,0),1)

```

```{python include=FALSE}
from sympy import *

a, b, c, w = symbols('a b c \omega', real=True, Positive=True)
t = symbols('t')
s = symbols('s')

d2y = symbols('\ddot{y}')
dy = symbols('\dot{y}')
dx = symbols('\dot{x}')
x = symbols('{x}')

edo = Eq(a*d2y,d*x+e*dx-b*dy-c*y)

reps = [(a,r.a), (b,r.b), (c,r.c), (w,r.w)]
edo = edo.subs(reps)

X = [Eq(a*s**2+b*s+c,0),
     Eq(a*s+b,0),
     Eq(a*s**2+c,b),
     Eq(s**2+b*s+c,0),
     Eq((s+a)**2+b*s+c,0),
     ]

X_str = ['$$' + latex(x.subs(reps).simplify()) + '$$' for x in X]
edo_str = latex(edo.subs(reps).simplify())
```

```{r}
A = answerlist(py$X_str, markup = "markdown")
```

Question
========

A equação característica do sistema:

$$`r a`\, \ddot{y}  = `r d`\, x + `r e`\,\dot{x} - b\, \dot{y} - c \, y$$

é descrita como:

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(py$X_str, markup = "markdown")
```


Meta-information
================
exname: lap_expcos
extype: schoice
exsolution: 1100000
exshuffle: 5
